FROM postgres:16

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        curl \
        openjdk-21-jre-headless \
    && rm -rf /var/lib/apt/lists/*
