# -*- coding: utf-8 -*-
"""
Structure-parameter measurement: align MTEF AST structure nodes (from the Go
mtefast exporter) against genuine MathType WMF glyph geometry, cut a ground-
truth box for every fraction template node, and measure micro-structure
parameters (bar overhang, numerator/bar/denominator gaps, math-axis offset).

Alignment model (round 2, derived from corpus evidence):
- MathType WMF emits glyphs grouped by font run, NOT in reading order, and
  NOT one baseline per MTEF LINE: ALL numerators at the same height share
  one baseline band, all denominators share another.
- Each MTEF LINE therefore corresponds to a CONTIGUOUS X-RANGE inside one
  baseline band whose x-sorted char string equals the LINE's direct char
  sequence (template-drawn glyphs like fence parens have no AST CHAR and
  stay unmatched).
- Matching is structure-guided: fraction numerator/denominator slot LINEs
  are matched as PAIRS (num band above den band, minimal x-center distance),
  then the root LINE and remaining LINEs are matched greedily. Identity is
  exact char-sequence equality; geometry is read off the matched range.

Method constraints (from review doc):
- measurements attach to MTEF TMPL nodes (tree-level), not baseline runs.
- train/validation split is deterministic (md5 of image name, 70/30); all
  report numbers are produced by this script (no manual analysis).
- five box semantics recorded separately; no cross-box conclusions.
  ink bbox (pixel layer) is null/TODO; renderer viewport is N/A for WMF GT.

Inputs:
    target/wmf-ruler/glyph-layouts.json   (regenerated by wmf_glyph_layout.py)
    target/wmf-ruler/ast.jsonl            (Go mtefast output)

Outputs:
    target/wmf-ruler/structure-measure.jsonl   per-fraction measurements
    target/wmf-ruler/structure_params.json     train-set median parameters
    docs/structure-params-round1.md            auto-generated report

Usage:
    python scripts/structure_measure.py
"""
from __future__ import annotations

import hashlib
import json
import math
import statistics
import sys
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from font_metrics import FontMetrics  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
LAYOUTS = ROOT / "target" / "wmf-ruler" / "glyph-layouts.json"
AST_JSONL = ROOT / "target" / "wmf-ruler" / "ast.jsonl"
OUT_JSONL = ROOT / "target" / "wmf-ruler" / "structure-measure.jsonl"
OUT_PARAMS = ROOT / "target" / "wmf-ruler" / "structure_params.json"
OUT_MD = ROOT / "docs" / "structure-params-round1.md"

CANON = {
    "-": "−", "‐": "−", "–": "−", "—": "−", "−": "−",
    "‘": "'", "’": "'", "′": "'",
}

# baseline clustering tolerance in pt (same band shares an exact y)
Y_TOL = 0.5


def canon(ch: str) -> str:
    return CANON.get(ch, ch)


# ---------------------------------------------------------------------------
# AST flattening: LINE nodes with DIRECT char sequences
# ---------------------------------------------------------------------------

def ast_char_text(node: dict) -> str:
    mc = node.get("mtcode")
    if mc is not None and 0x20 <= mc < 0xD800:
        return canon(chr(mc))
    t = node.get("text") or ""
    if len(t) == 1:
        return canon(t)
    return t


def flatten_ast(root: dict):
    """Returns (lines, tmpls).

    lines: [{nid, seq(direct CHARs only), slot_of{tmpl_nid: slot_index},
             parent_tmpl, depth}]
    tmpls: [{nid, selectorName, variation, slot_lines([nid,...]),
             parent_tmpl, depth}]
    """
    lines: list[dict] = []
    tmpls: list[dict] = []
    counter = [0]

    def direct_seq(node: dict) -> str:
        out = []
        for c in node.get("children") or []:
            if c.get("tag") == "CHAR":
                out.append(ast_char_text(c))
        return "".join(out)

    def walk(node: dict, depth: int, parent_tmpl, slot_of: dict) -> None:
        nid = counter[0]
        counter[0] += 1
        tag = node.get("tag")
        if tag == "LINE":
            lines.append({
                "nid": nid,
                "seq": direct_seq(node),
                "slot_of": dict(slot_of),
                "parent_tmpl": parent_tmpl,
                "depth": depth,
            })
            for c in node.get("children") or []:
                walk(c, depth + 1, parent_tmpl, slot_of)
        elif tag == "TMPL":
            slot_lines = []
            slot_idx = 0
            for c in node.get("children") or []:
                if c.get("tag") == "LINE":
                    child_slot = dict(slot_of)
                    child_slot[nid] = slot_idx
                    before = len(lines)
                    walk(c, depth + 1, nid, child_slot)
                    slot_lines.append(lines[before]["nid"]
                                      if len(lines) > before else None)
                    slot_idx += 1
                else:
                    walk(c, depth + 1, nid, slot_of)
            tmpls.append({
                "nid": nid,
                "selectorName": node.get("selectorName") or "",
                "variation": node.get("variation") or 0,
                "slot_lines": slot_lines,
                "parent_tmpl": parent_tmpl,
                "depth": depth,
            })
        else:
            for c in node.get("children") or []:
                walk(c, depth + 1, parent_tmpl, slot_of)

    walk(root, 0, None, {})
    return lines, tmpls


# ---------------------------------------------------------------------------
# WMF baseline bands
# ---------------------------------------------------------------------------

def cluster_glyphs(glyphs, font_metrics=None, width_table=None,
                   width_default=0.55):
    """Cluster glyph indices by baseline y_pt (merge within Y_TOL).

    Per-glyph tight right edge `xe` uses real font advances (font property):
    the recorded dx is origin spacing that may include inter-expression
    spacing (several expressions share one EXTTEXTOUT run), so it must not
    be used for box extents or pair-scoring centers.
    """
    gs = sorted((i for i, g in enumerate(glyphs) if "y_pt" in g),
                key=lambda i: glyphs[i]["y_pt"])
    clusters = []
    for i in gs:
        y = glyphs[i]["y_pt"]
        if clusters and abs(clusters[-1]["y"] - y) <= Y_TOL:
            clusters[-1]["idxs"].append(i)
            clusters[-1]["y"] = statistics.median(
                glyphs[j]["y_pt"] for j in clusters[-1]["idxs"])
        else:
            clusters.append({"y": y, "idxs": [i]})
    for c in clusters:
        c["idxs"].sort(key=lambda i: glyphs[i]["x_pt"])
        c["seq"] = "".join(canon(glyphs[i]["ch"]) for i in c["idxs"])
        c["attrs"] = [{"ch": glyphs[i]["ch"], "hex": glyphs[i].get("hex"),
                       "face": glyphs[i].get("font"),
                       "italic": bool(glyphs[i].get("italic"))}
                      for i in c["idxs"]]
        c["xs"] = [glyphs[i]["x_pt"] for i in c["idxs"]]
        c["size_pt"] = statistics.median(
            glyphs[i].get("size_pt") or 0 for i in c["idxs"])

        def tight(i):
            g = glyphs[i]
            r = None
            if font_metrics is not None:
                r = font_metrics.advance_ratio(
                    g["ch"], g.get("hex"), g.get("font"),
                    bool(g.get("italic")))
            if r is None and width_table is not None:
                r = width_table.get(canon(g["ch"]), width_default)
            if r is None:
                r = width_default
            return g["x_pt"] + r * (g.get("size_pt") or c["size_pt"])

        c["xe"] = [tight(i) for i in c["idxs"]]
    return clusters


def find_occurrences(clusters, seq):
    """All (cluster_idx, start_pos) where seq occurs contiguously."""
    out = []
    if not seq:
        return out
    for ci, c in enumerate(clusters):
        start = c["seq"].find(seq)
        while start >= 0:
            out.append((ci, start))
            start = c["seq"].find(seq, start + 1)
    return out


def match_lines(lines, tmpls, clusters, h_rules):
    """Structure-guided matching. Returns {line_nid: (cluster_idx, start)}.

    Pass 1: fraction num/den slot LINEs as pairs (num band above den band,
    minimal x-center distance, bonus when a real fraction bar lies between
    the bands and overlaps the pair span). Pass 2: remaining LINEs,
    longest-sequence-first greedy over free occurrences.
    """
    used = [bytearray(len(c["idxs"])) for c in clusters]
    occ = {ln["nid"]: find_occurrences(clusters, ln["seq"])
           for ln in lines if ln["seq"]}
    line_by_nid = {ln["nid"]: ln for ln in lines}
    mapping = {}

    def free(ci, start, n):
        return all(not used[ci][start + k] for k in range(n))

    def claim(ci, start, n):
        for k in range(n):
            used[ci][start + k] = 1

    def xcenter(ci, start, n):
        c = clusters[ci]
        return (c["xs"][start] + c["xe"][start + n - 1]) / 2.0

    def rule_between(y_num, y_den, xl, xr):
        """A real bar between the bands, mostly contained in the pair span."""
        for r in h_rules:
            ry = r["y1_pt"]
            rx1, rx2 = sorted((r["x1_pt"], r["x2_pt"]))
            if not (min(y_num, y_den) < ry < max(y_num, y_den)):
                continue
            span = xr - xl
            if span <= 0 or not (xl <= (rx1 + rx2) / 2 <= xr):
                continue
            ov = min(xr, rx2) - max(xl, rx1)
            if ov > 0.5 * min(span, rx2 - rx1):
                return True
        return False

    # pass 1: fraction slot pairs
    for t in tmpls:
        if t["selectorName"] != "tmFRACT" or len(t["slot_lines"]) != 2:
            continue
        num_nid, den_nid = t["slot_lines"]
        if num_nid not in occ or den_nid not in occ:
            continue
        n_seq = line_by_nid[num_nid]["seq"]
        d_seq = line_by_nid[den_nid]["seq"]
        best, best_score = None, None
        for nci, ns in occ[num_nid]:
            if not free(nci, ns, len(n_seq)):
                continue
            for dci, ds in occ[den_nid]:
                if dci == nci or not free(dci, ds, len(d_seq)):
                    continue
                if clusters[nci]["y"] >= clusters[dci]["y"]:
                    continue
                xl = min(clusters[nci]["xs"][ns], clusters[dci]["xs"][ds])
                xr = max(clusters[nci]["xe"][ns + len(n_seq) - 1],
                         clusters[dci]["xe"][ds + len(d_seq) - 1])
                score = abs(xcenter(nci, ns, len(n_seq))
                            - xcenter(dci, ds, len(d_seq)))
                if rule_between(clusters[nci]["y"], clusters[dci]["y"], xl, xr):
                    score *= 0.2  # prefer pairs anchored on a real bar
                if best_score is None or score < best_score:
                    best_score = score
                    best = ((nci, ns), (dci, ds))
        if best:
            mapping[num_nid] = best[0]
            mapping[den_nid] = best[1]
            claim(best[0][0], best[0][1], len(n_seq))
            claim(best[1][0], best[1][1], len(d_seq))

    # pass 2: root LINE first, then the rest (longest seq first)
    rest = [ln for ln in lines if ln["seq"] and ln["nid"] not in mapping]
    rest.sort(key=lambda ln: (ln["parent_tmpl"] is not None, -len(ln["seq"])))
    for ln in rest:
        cands = [(ci, s) for ci, s in occ.get(ln["nid"], [])
                 if free(ci, s, len(ln["seq"]))]
        if not cands:
            continue
        # prefer the candidate closest in x to already-matched siblings
        chosen = cands[0]
        mapping[ln["nid"]] = chosen
        claim(chosen[0], chosen[1], len(ln["seq"]))
    return mapping


# ---------------------------------------------------------------------------
# Fraction measurement
# ---------------------------------------------------------------------------

def measure_formula(image, glyphs, rules, lines, tmpls, line_map, clusters,
                    font_metrics, width_table, width_default):
    h_rules = [r for r in rules
               if r["kind"] == "line" and abs(r["y1_pt"] - r["y2_pt"]) < 0.2
               and abs(r["x2_pt"] - r["x1_pt"]) > 2.0]
    line_by_nid = {ln["nid"]: ln for ln in lines}

    def glyph_width(attrs, size_pt):
        # true advance from the TTF the glyph came from (font property);
        # fall back to the corpus ratio table, then the global default
        r = font_metrics.advance_ratio(attrs["ch"], attrs["hex"],
                                       attrs["face"], attrs["italic"])
        if r is None:
            r = width_table.get(canon(attrs["ch"]), width_default)
        return r * size_pt

    def geom(nid):
        """(baseline_y, left, right, size_pt) for a matched LINE.

        Right edge: origin spacing inside the matched contiguous range is
        exact; the range-final glyph's width comes from real font metrics
        (its recorded dx is the advance to whatever follows in the run,
        which may be a different expression entirely).
        """
        m = line_map.get(nid)
        if m is None:
            return None
        ci, start = m
        c = clusters[ci]
        n = len(line_by_nid[nid]["seq"])
        right = None
        for p in range(start, start + n):
            if p + 1 < start + n:
                edge = c["xs"][p + 1]
            else:
                edge = c["xs"][p] + glyph_width(c["attrs"][p], c["size_pt"])
            right = edge if right is None else max(right, edge)
        return {"y": c["y"], "left": c["xs"][start],
                "right": round(right, 3) if right is not None else None,
                "size_pt": c["size_pt"]}

    main_baseline = None
    for ln in lines:
        if ln["parent_tmpl"] is None and ln["nid"] in line_map:
            main_baseline = geom(ln["nid"])["y"]
            break
    # no fallback: axis_offset is undefined when the root LINE is unmatched
    # (e.g. the formula is a bare fraction with no top-level chars)

    out = []
    for t in tmpls:
        if t["selectorName"] != "tmFRACT":
            continue
        if len(t["slot_lines"]) != 2 or any(n is None for n in t["slot_lines"]):
            out.append({"image": image, "nid": t["nid"],
                        "skipped": f"slot lines {t['slot_lines']}"})
            continue
        num_nid, den_nid = t["slot_lines"]
        num_g, den_g = geom(num_nid), geom(den_nid)
        if num_g is None or den_g is None:
            out.append({"image": image, "nid": t["nid"],
                        "skipped": "num/den LINE unmatched",
                        "num_seq": line_by_nid[num_nid]["seq"],
                        "den_seq": line_by_nid[den_nid]["seq"]})
            continue

        # visual box of a slot = union of matched ranges of every LINE whose
        # slot chain passes through this TMPL's slot 0 (num) / slot 1 (den)
        def slot_box(slot_idx):
            lefts, rights = [], []
            for ln in lines:
                if ln["slot_of"].get(t["nid"]) != slot_idx:
                    continue
                g = geom(ln["nid"])
                if g is None:
                    continue
                lefts.append(g["left"])
                rights.append(g["right"])
            if not lefts:
                return None
            return {"left": round(min(lefts), 3),
                    "right": round(max(rights), 3), "n": len(lefts)}

        num_box, den_box = slot_box(0), slot_box(1)
        if num_box is None or den_box is None:
            out.append({"image": image, "nid": t["nid"],
                        "skipped": "empty slot box"})
            continue
        lo = min(num_box["left"], den_box["left"])
        hi = max(num_box["right"], den_box["right"])

        best, best_ov = None, 0.0
        for r in h_rules:
            rx1, rx2 = sorted((r["x1_pt"], r["x2_pt"]))
            ry = r["y1_pt"]
            if not (min(num_g["y"], den_g["y"]) - 0.5
                    <= ry <= max(num_g["y"], den_g["y"]) + 0.5):
                continue
            ov = min(hi, rx2) - max(lo, rx1)
            if ov > best_ov:
                best, best_ov = r, ov
        rec = {
            "image": image, "nid": t["nid"], "variation": t["variation"],
            "depth": t["depth"],
            "nested": t["parent_tmpl"] is not None,
            "identity": "exact",
            "boxes": {
                "ink_bbox_px": None,          # pixel layer: TODO
                "renderer_viewport_pt": None,  # N/A for WMF GT
                "wmf_placeable_bbox_pt": None,  # filled by caller
                "num_glyph_box_pt": num_box,
                "den_glyph_box_pt": den_box,
                "num_baseline": round(num_g["y"], 3),
                "den_baseline": round(den_g["y"], 3),
                "main_baseline": (round(main_baseline, 3)
                                  if main_baseline is not None else None),
            },
        }
        if best is not None:
            bar_y = best["y1_pt"]
            bx1, bx2 = sorted((best["x1_pt"], best["x2_pt"]))
            wide_left = min(num_box["left"], den_box["left"])
            wide_right = max(num_box["right"], den_box["right"])
            size = num_g["size_pt"] or den_g["size_pt"]
            rec["bar"] = {"y": round(bar_y, 3), "x1": round(bx1, 3),
                          "x2": round(bx2, 3), "len": round(bx2 - bx1, 3)}
            rec["params"] = {
                "bar_overhang_l": round(wide_left - bx1, 3),
                "bar_overhang_r": round(bx2 - wide_right, 3),
                "num_overhang_l": round(num_box["left"] - bx1, 3),
                "num_overhang_r": round(bx2 - num_box["right"], 3),
                "den_overhang_l": round(den_box["left"] - bx1, 3),
                "den_overhang_r": round(bx2 - den_box["right"], 3),
                "gap_num_bar": round(bar_y - num_g["y"], 3),
                "gap_bar_den": round(den_g["y"] - bar_y, 3),
                "num_den_gap": round(den_g["y"] - num_g["y"], 3),
                # axis_offset is only structurally meaningful for a
                # root-level fraction (main baseline unambiguous)
                "axis_offset": (round(main_baseline - bar_y, 3)
                                if main_baseline is not None
                                and t["parent_tmpl"] is None else None),
                "size_pt": round(size, 3),
            }
            # deterministic quarantine (no manual triage): a fraction whose
            # bar is not mostly inside its slot box, or whose overhang
            # exceeds 5pt (MathType overhang is sub-pt..~2pt), is an x-side
            # matching failure -- excluded from all statistics, listed in
            # the report.
            bar_len = bx2 - bx1
            containment = best_ov / bar_len if bar_len > 0 else 0
            if containment < 0.6:
                rec["quarantine"] = f"bar-not-contained({containment:.2f})"
            elif (abs(rec["params"]["bar_overhang_l"]) > 5
                  or abs(rec["params"]["bar_overhang_r"]) > 5):
                rec["quarantine"] = "overhang-outlier"
        else:
            rec["bar"] = None
        out.append(rec)
    return out


# ---------------------------------------------------------------------------
# Bucketing, stats, report
# ---------------------------------------------------------------------------

def bucket_of(n_fract, n_rules, any_nested):
    if n_fract == 1 and n_rules <= 1:
        return "single"
    if any_nested:
        return "nested"
    if n_rules >= 3:
        return "chain"
    return "multi"


def quantiles(vals):
    vals = sorted(vals)
    if not vals:
        return {}

    def q(p):
        k = (len(vals) - 1) * p
        f = math.floor(k)
        c = min(f + 1, len(vals) - 1)
        return round(vals[f] + (vals[c] - vals[f]) * (k - f), 3)

    return {"n": len(vals), "min": round(vals[0], 3), "p25": q(0.25),
            "median": q(0.5), "p75": q(0.75), "p95": q(0.95),
            "max": round(vals[-1], 3)}


def main() -> int:
    layouts = json.loads(LAYOUTS.read_text(encoding="utf-8"))
    asts = {}
    for line in AST_JSONL.read_text(encoding="utf-8").splitlines():
        rec = json.loads(line)
        if rec.get("ok"):
            asts[Path(rec["path"]).stem] = rec["ast"]

    def split_of(image):
        h = int(hashlib.md5(image.encode()).hexdigest(), 16)
        return "train" if h % 10 < 7 else "val"

    def h_rules_of(rules):
        return [r for r in rules
                if r["kind"] == "line" and abs(r["y1_pt"] - r["y2_pt"]) < 0.2
                and abs(r["x2_pt"] - r["x1_pt"]) > 2.0]

    # pass 0: per-char advance-width table from TRAIN formulas only.
    # Source: dx_pt of glyphs that are NOT last in their EXTTEXTOUT run
    # (the last entry is the advance to the next run, not a width).
    samples: dict[str, list[float]] = {}
    all_ratios: list[float] = []
    for f in layouts["formulas"]:
        image = Path(f["source"]).stem
        if split_of(image) != "train":
            continue
        for g in f["glyphs"]:
            if g.get("last_in_run") or g.get("dx_pt") is None:
                continue
            size = g.get("size_pt") or 0
            if size <= 0:
                continue
            ratio = g["dx_pt"] / size
            if 0.1 < ratio < 1.5:
                samples.setdefault(canon(g["ch"]), []).append(ratio)
                all_ratios.append(ratio)
    width_table = {ch: statistics.median(v) for ch, v in samples.items()}
    width_default = statistics.median(all_ratios) if all_ratios else 0.55
    font_metrics = FontMetrics()

    all_meas, per_formula, skipped = [], [], []
    for f in layouts["formulas"]:
        image = Path(f["source"]).stem
        ast = asts.get(image)
        if ast is None:
            continue
        lines, tmpls = flatten_ast(ast)
        clusters = cluster_glyphs(f["glyphs"], font_metrics,
                                  width_table, width_default)
        line_map = match_lines(lines, tmpls, clusters, h_rules_of(f["rules"]))
        n_lines = sum(1 for ln in lines if ln["seq"])
        n_matched = sum(1 for ln in lines
                        if ln["seq"] and ln["nid"] in line_map)
        meas = measure_formula(image, f["glyphs"], f["rules"], lines, tmpls,
                               line_map, clusters, font_metrics,
                               width_table, width_default)
        for m in meas:
            if "boxes" in m:
                m["boxes"]["wmf_placeable_bbox_pt"] = f.get("placeable_bbox_pt")
            else:
                skipped.append(m)
        n_fract = sum(1 for t in tmpls if t["selectorName"] == "tmFRACT")
        n_rules = sum(1 for r in f["rules"]
                      if r["kind"] == "line" and abs(r["y1_pt"] - r["y2_pt"]) < 0.2
                      and abs(r["x2_pt"] - r["x1_pt"]) > 2.0)
        any_nested = any(t["selectorName"] == "tmFRACT" and t["parent_tmpl"]
                         is not None for t in tmpls)
        bucket = bucket_of(n_fract, n_rules, any_nested)
        split = split_of(image)
        for m in meas:
            if "params" in m:
                m["bucket"] = bucket
                m["split"] = split
        all_meas.extend(m for m in meas if "params" in m)
        pf = {"image": image, "bucket": bucket,
              "n_fract": n_fract, "n_rules": n_rules,
              "line_match": f"{n_matched}/{n_lines}", "split": split}
        # preview-box truth: placeable bbox vs main baseline (five-box
        # semantics: WMF placeable bbox + main baseline, no cross-box claims)
        mb = next((m["boxes"]["main_baseline"] for m in meas
                   if "boxes" in m
                   and m["boxes"].get("main_baseline") is not None), None)
        bbox = f.get("placeable_bbox_pt")
        if bbox and mb is not None:
            pf["box_height_pt"] = round(bbox[3] - bbox[1], 3)
            pf["above_pt"] = round(mb - bbox[1], 3)
            pf["below_pt"] = round(bbox[3] - mb, 3)
        per_formula.append(pf)

    OUT_JSONL.parent.mkdir(parents=True, exist_ok=True)
    with OUT_JSONL.open("w", encoding="utf-8") as fh:
        for m in all_meas:
            fh.write(json.dumps(m, ensure_ascii=False) + "\n")

    param_names = ["bar_overhang_l", "bar_overhang_r",
                   "num_overhang_l", "num_overhang_r",
                   "den_overhang_l", "den_overhang_r",
                   "gap_num_bar", "gap_bar_den", "num_den_gap", "axis_offset"]
    params = {"split": "md5(image)%10<7 -> train (70/30 deterministic)",
              "unit": "pt",
              "width_table_default_ratio": round(width_default, 4),
              "width_table_chars": len(width_table),
              "buckets": {}}
    for bucket in ("single", "nested", "chain", "multi"):
        rows = [m for m in all_meas if m["bucket"] == bucket
                and m["split"] == "train" and "quarantine" not in m]
        if not rows:
            continue
        entry = {"n_train": len(rows)}
        size = statistics.median(r["params"]["size_pt"] for r in rows
                                 if r["params"]["size_pt"])
        entry["size_pt_median"] = round(size, 3)
        for p in param_names:
            vals = [r["params"][p] for r in rows
                    if r["params"].get(p) is not None]
            if not vals:
                continue
            entry[p] = quantiles(vals)
            if size:
                entry[p + "_per_size"] = quantiles([v / size for v in vals])
        params["buckets"][bucket] = entry

    # preview-box truth per bucket (train only): placeable bbox height and
    # its split into above/below the main baseline -- these feed the
    # renderer's FamilyMetrics heights.
    preview_boxes = {}
    for bucket in ("single", "nested", "chain", "multi"):
        rows = [p for p in per_formula if p["bucket"] == bucket
                and p["split"] == "train" and "box_height_pt" in p]
        if not rows:
            continue
        entry = {"n_train": len(rows)}
        for k in ("box_height_pt", "above_pt", "below_pt"):
            entry[k] = quantiles([p[k] for p in rows])
        preview_boxes[bucket] = entry
    params["preview_boxes"] = preview_boxes
    OUT_PARAMS.write_text(json.dumps(params, ensure_ascii=False, indent=1),
                          encoding="utf-8")

    val_report = {}
    for bucket in ("single", "nested", "chain", "multi"):
        tr = params["buckets"].get(bucket)
        if not tr:
            continue
        rows = [m for m in all_meas if m["bucket"] == bucket
                and m["split"] == "val" and "quarantine" not in m]
        entry = {"n_val": len(rows)}
        for p in param_names:
            if p not in tr:
                continue
            med = tr[p]["median"]
            res = [abs(r["params"][p] - med) for r in rows
                   if r["params"].get(p) is not None]
            if res:
                entry[p + "_absres"] = quantiles(res)
        # validation residual for preview box height
        pb = preview_boxes.get(bucket)
        if pb:
            vrows = [p for p in per_formula if p["bucket"] == bucket
                     and p["split"] == "val" and "box_height_pt" in p]
            res = [abs(p["box_height_pt"] - pb["box_height_pt"]["median"])
                   for p in vrows]
            if res:
                entry["box_height_absres"] = quantiles(res)
        val_report[bucket] = entry

    # ---- report ----------------------------------------------------------
    n_images = len(per_formula)
    buckets_c = Counter(p["bucket"] for p in per_formula)
    bad_lines = [p for p in per_formula
                 if p["line_match"].split("/")[0] != p["line_match"].split("/")[1]]
    lines_out = []
    lines_out.append("# 结构参数测量报告（round 4）")
    lines_out.append("")
    lines_out.append("本报告由 `scripts/structure_measure.py` 自动生成，所有数字由脚本计算。")
    lines_out.append("")
    lines_out.append("对齐模型：WMF 字形按字体系输出（非阅读顺序），且同高度的所有分子共享一条基线带、"
                     "所有分母共享另一条。每个 MTEF LINE 对应某基线带内一段连续 x 区间，其 x 排序字符"
                     "序列与 LINE 的直接字符序列完全相等（模板绘制的括号等字形无 AST CHAR，保持未匹配）。"
                     "分式分子/分母槽 LINE 成对匹配（分子带在分母带上方、x 中心距离最小），"
                     "其余 LINE 贪心匹配。恒等为精确字符序列相等，几何从匹配区间读取。")
    lines_out.append("")
    lines_out.append("## 数据概览")
    lines_out.append("")
    lines_out.append(f"- 公式数（WMF 真值 × MTEF AST 配对）：{n_images}")
    lines_out.append(f"- 分式节点测量数（含分数线归属成功）：{len(all_meas)}")
    lines_out.append(f"- 分式节点跳过（LINE 未匹配/槽缺失）：{len(skipped)}")
    lines_out.append(f"- 存在未匹配 LINE 的公式：{len(bad_lines)}")
    if bad_lines:
        lines_out.append(f"  - 示例：{', '.join(p['image'] + '(' + p['line_match'] + ')' for p in bad_lines[:10])}")
    lines_out.append(f"- 结构分桶（按公式）："
                     + ", ".join(f"{k}={v}" for k, v in sorted(buckets_c.items())))
    lines_out.append("")
    lines_out.append("切分：md5(image) % 10 < 7 → train（70/30 确定性切分）。")
    lines_out.append(f"右边缘/紧盒：区间内用原点间距（精确）；区间末字形宽度来自真实字体度量"
                     f"（fontTools 读 times/timesi/symbol.ttf，纯字体属性，无训练泄漏），"
                     f"语料宽度表（{len(width_table)} 字符，默认 {round(width_default, 4)}）仅作回退——"
                     f"因为 MathType 的 dx 是原点间距，多表达式共享运行时含表达式间隙，"
                     f"TA_UPDATECP 末字形 dx 更是到下一运行锚点的距离。")
    lines_out.append("axis_offset 仅对根级分式定义（裸分式或堆叠行内分式为 null/不做结论）。")
    lines_out.append("五框语义分开记录：ink bbox（像素层，TODO）、renderer viewport（不适用）、"
                     "WMF placeable bbox、分子/分母字形盒、基线/数学轴。本报告不做跨框结论。")
    lines_out.append("")
    lines_out.append("## 预览框真值（WMF placeable bbox，train）")
    lines_out.append("")
    lines_out.append("above = 主基线 → bbox 顶；below = 主基线 → bbox 底。供渲染器 FamilyMetrics 高度使用。")
    for bucket, e in preview_boxes.items():
        lines_out.append("")
        lines_out.append(f"### {bucket}（n_train={e['n_train']}）")
        lines_out.append("")
        lines_out.append("| 参数 | p25 | 中位 | p75 | p95 |")
        lines_out.append("|---|---|---|---|---|")
        for k in ("box_height_pt", "above_pt", "below_pt"):
            q = e[k]
            lines_out.append(f"| {k} | {q['p25']} | {q['median']} | {q['p75']} | {q['p95']} |")
        vb = val_report.get(bucket, {}).get("box_height_absres")
        if vb:
            lines_out.append(f"| 验证集高度残差 | 中位 {vb['median']} | p75 {vb['p75']} "
                             f"| p95 {vb['p95']} | max {vb['max']} |")
    lines_out.append("")
    lines_out.append("## 训练集参数（pt，另附 per-size 归一）")
    for bucket, e in params["buckets"].items():
        lines_out.append("")
        lines_out.append(f"### {bucket}（n_train={e['n_train']}, "
                         f"size_pt 中位={e['size_pt_median']}）")
        lines_out.append("")
        lines_out.append("| 参数 | min | p25 | 中位 | p75 | p95 | max | 中位/size |")
        lines_out.append("|---|---|---|---|---|---|---|---|")
        for p in param_names:
            if p not in e:
                continue
            q = e[p]
            ns = e.get(p + "_per_size", {}).get("median")
            lines_out.append(f"| {p} | {q['min']} | {q['p25']} | {q['median']} | "
                             f"{q['p75']} | {q['p95']} | {q['max']} | {ns} |")
    lines_out.append("")
    lines_out.append("## 验证集残差（|实测 − 训练集中位|，pt）")
    for bucket, e in val_report.items():
        lines_out.append("")
        lines_out.append(f"### {bucket}（n_val={e['n_val']}）")
        lines_out.append("")
        lines_out.append("| 参数 | 中位 | p75 | p95 | max |")
        lines_out.append("|---|---|---|---|---|")
        for p in param_names:
            k = p + "_absres"
            if k not in e:
                continue
            q = e[k]
            lines_out.append(f"| {p} | {q['median']} | {q['p75']} | {q['p95']} | {q['max']} |")
    if skipped:
        lines_out.append("")
        lines_out.append("## 跳过的分式节点（需后续处理）")
        lines_out.append("")
        reasons = Counter(m.get("skipped", "?") for m in skipped)
        for reason, n in reasons.most_common():
            lines_out.append(f"- {reason}：{n}")
    quarantined = [m for m in all_meas if "quarantine" in m]
    if quarantined:
        lines_out.append("")
        lines_out.append("## 隔离记录（确定性规则，自动剔除出统计）")
        lines_out.append("")
        lines_out.append("规则：分数线未大部分落入槽盒（containment < 0.6）或 |bar_overhang| > 5pt"
                         "（MathType 超出量在亚 pt~2pt 量级）→ 判为 x 侧匹配失败，"
                         "剔除出全部统计并在此列出。axis_offset 仅对根级分式定义。")
        lines_out.append("")
        qreasons = Counter(m["quarantine"].split("(")[0] for m in quarantined)
        for reason, n in qreasons.most_common():
            imgs = sorted(set(m["image"] for m in quarantined
                              if m["quarantine"].split("(")[0] == reason))
            lines_out.append(f"- {reason}：{n}（{len(imgs)} 个公式："
                             f"{', '.join(imgs[:12])}{'…' if len(imgs) > 12 else ''}）")
    lines_out.append("")
    lines_out.append(f"产物：`{OUT_JSONL.relative_to(ROOT)}`、"
                     f"`{OUT_PARAMS.relative_to(ROOT)}`。")
    OUT_MD.write_text("\n".join(lines_out) + "\n", encoding="utf-8")

    print(f"formulas={n_images} fractions={len(all_meas)} skipped={len(skipped)} "
          f"quarantined={len(quarantined)} bad_line_formulas={len(bad_lines)}")
    for bucket, e in val_report.items():
        gn = e.get("gap_num_bar_absres", {})
        print(f"  {bucket}: n_val={e['n_val']} gap_num_bar absres "
              f"median={gn.get('median')} p95={gn.get('p95')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
